### ISSUE TITLE
escaping '@'?

### ISSUE THREAD

**Issue by mjibson** [cortesi/modd#35]
I'm trying to use modd with curl's "read a file" option. curl will read a file from disk when its argument starts with `@`. This conflicts with modd's conf, though, which thinks `@` is for its own configuration. I wasn't able to find an escape option to prevent modd from interpreting the `@`. Is there a way to do this?

**Comment by cortesi** [comment]
Hi there. At the moment, I'm afraid this is a simple regex replacement with no escaping. We certainly should make this safer, though. One option is to introduce escaping. Another is to punt again and make the replacement indicator more elaborate and less likely to clash ("{{variable}}"?). 

Patches gladly accepted. :) Otherwise, I'll put this on the todo list for the next release.

**Comment by ksonj** [comment]
Does this mean it is currently impossible to start a daemon with something like

    {
         daemon: service --database-uri=mysql://user@localhost ...
     }

because `@localhost` is interpreted as a variable?

**Comment by ksonj** [comment]
Storing the URI in variable and the using that variable is my current workaround

    @database = mysql://user@localhost/db

    {
         daemon: service --database=@database ..
    }
