### ISSUE TITLE
modd shell doesn't currently work on Windows, needs upstream fixes

### ISSUE THREAD

**Issue by grandopener** [cortesi/modd#63]
Hey there!  I just found modd and it's (almost) exactly what I'm looking for.  Love what I see.  Just wish it actually worked on windows.  :)

I did some digging.  See: https://github.com/mvdan/sh/issues/325

In particular, mvdan.cc/sh may fail to find environment variable for PATH, which causes the modd shell to fail to find the go executable (or anything else).  Even if you hard-code the path to the go executable in the .conf file (or fiddle with the capitalization of your PATH environment variable to get it to work), modd shell still fails to find an appropriate Temp directory.  (Perhaps this is because it cannot read the TMP environment variable?  I was unable to determine where exactly that process breaks down.)

End result: modd shell basically unusable for anything on Windows until these upstream fixes are merged.

Challenge part 2: those fixes are not part of an official upstream release yet.  modd will need to update to mvdan.cc/sh v2.6.2 or as soon as it is available.  (Or consider updating to a git hash that has that fix.)

For the time being I find I am forced to use `@shell=powershell` for anything to work on windows.  That's a pain point for things that are supposed to be cross platform.  Idea: this would be somewhat less painful if I could (on windows) write something like `PS> modd -shell=powershell` and still share a cross-platform modd.conf file.

**Comment by cortesi** [comment]
Hi Cary. Thanks for the careful and complete analysis here. We can fix the immediate issue by pinning to the **mvdan/sh** master until their next release.  If you have a moment, it would be great if you could submit a unit test that triggers the problem, so we can catch it in CI if it crops up again in future. I'll cut a new release of modd soon after this to fix the Windows issue for users of the binaries. 

I'm in two minds about a shell over-ride flag. I can see the utility, but the specific use case would mean the modd.conf would have to be written in a tricky shared subset of sh and powershell. I think making sure our built-in shell works properly on all platforms is the right way to go. Eventually, I might remove support for external shells altogether, so that you never need to rely on anything outside of modd to run a conf file.

**Comment by grandopener** [comment]
Hey there.  I came up with a test that exhibits the problem, but it still exhibits the problem even on the most recent version, so there may be some deeper issue here that just updating to latest mvdan.cc/sh.  Here's the test (put in `shell/shell_test.go`):
```
func TestCaseInsensitivePath(t *testing.T) {
	if runtime.GOOS != "windows" {
		t.Skip("skipping - only windows has case insensitive PATH")
	}

	oldpath := os.Getenv("PATH")
	fixpath := func() {
		os.Unsetenv("Path")
		os.Setenv("PATH", oldpath)
	}
	defer fixpath()
	os.Unsetenv("PATH")
	os.Setenv("Path", fmt.Sprintf("%s%ctrigger-text", oldpath, os.PathListSeparator))

	shellTesting = true

	pathTest := cmdTest{
		name:   "path-test",
		cmd:    "echo $PATH",
		logHas: "trigger-text",
	}
	sh := "modd"
	t.Run(
		"modd/path-capitalization",
		func(t *testing.T) {
			if _, err := CheckShell(sh); err != nil {
				t.Skipf("skipping - %s", err)
			}
			testCmd(t, sh, pathTest)
		},
	)
}
```

It seems noteworthy that the most recent `mvdan.cc/sh/cmd/gosh` experimental shell does _not_ appear to exhibit this problem.  I don't have any more time to hack on this right now, but I'll try to come back to it later.

**Comment by cortesi** [comment]
This is fixed on master. I've committed your test to the repo, and it is now run during CI. Thanks for reporting!
